name = "Julia_starter_projects"
uuid = "18dd2fa3-96e4-4bc7-a92a-f245d0b5ea2b"
authors = ["edoch <edo_chio@hotmail.it>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
